# Add binding to reload tmux.conf for fast, iterative development
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Turn on mouse mode
set -g mouse on

# Shhhh...
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Longer history
set-option -g history-limit 5000

# Start indexing from 1.
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Better splits
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# New window starts at $HOME.
bind c new-window -c "#{pane_current_path}"

# Space to toggle between two windows/panes
bind C-b last-window
bind-key C-Space switch-client -l

# Statusline
set -g status-justify centre
set -g status-style fg=white,bg=black

# Highlight the current window.
setw -g window-status-current-style fg=white,bright
setw -g status-left-length 20
setw -g status-right-length 20
setw -g status-left " [#S] "
setw -g status-right " [%H:%M] "
