export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

# Exports
export TERMINAL="alacritty"
export EDITOR="nvim"
export DOTFILES="$HOME/dots"

# Aliases
alias v="nvim"
alias ls="LC_COLLATE=C ls --color --group-directories-first"
alias lsa="LC_COLLATE=C ls -a --color --group-directories-first"
alias l="LC_COLLATE=C ls --color -lh --group-directories-first"
alias ll="LC_COLLATE=C ls --color -lah --group-directories-first"
alias la="LC_COLLATE=C ls --color -ah --group-directories-first"
alias lt="tree -C --gitignore"
alias lt2="tree -C -L 2 --gitignore"
alias lt3="tree -C -L 3 --gitignore"
alias lta="tree -C -a --gitignore"
alias lta2="tree -C -a -L 2 --gitignore"
alias lta3="tree -C -a -L 3 --gitignore"
alias ltd="tree -C -d --gitignore"
alias ltd2="tree -C -d -L 2 --gitignore"
alias ltd3="tree -C -d -L 3 --gitignore"
alias cat="bat --plain"
alias lg="lazygit"
alias update="sudo nixos-rebuild switch";

# Plugins
source $DOTFILES/dotfiles/antigen.zsh
antigen bundle fzf
antigen bundle ssh-agent
antigen apply

# Enable starship
eval "$(starship init zsh)"
