# PATH
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/work/scripts:$PATH"

# EXPORTS
export EDITOR="nvim"
export DOTFILES="$HOME/dots"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
source $HOME/.work.zsh

# ALIASES
alias v="nvim"
alias vd="nvim ."
alias vi="nvim"
alias vim="nvim"
alias lg="lazygit"
alias lzd="lazydocker"
alias cat="bat --plain"
alias update="sudo nixos-rebuild switch";
alias ls="LC_COLLATE=C ls --color --group-directories-first"
alias lsa="LC_COLLATE=C ls -a --color --group-directories-first"
alias l="LC_COLLATE=C ls --color -lh --group-directories-first"
alias ll="LC_COLLATE=C ls --color -lah --group-directories-first"
alias la="LC_COLLATE=C ls --color -ah --group-directories-first"
alias lt="tree -C --gitignore"
alias lt2="tree -C -L 2 --gitignore"
alias lt3="tree -C -L 3 --gitignore"
alias lta="tree -C -a --gitignore"
alias lta2="tree -C -a -L 2 --gitignore"
alias lta3="tree -C -a -L 3 --gitignore"
alias ltd="tree -C -d --gitignore"
alias ltd2="tree -C -d -L 2 --gitignore"
alias ltd3="tree -C -d -L 3 --gitignore"
alias yank="xclip -sel clipboard"
alias dstop="docker ps -aq | xargs -r docker stop"
alias dpurge="docker ps -aq | xargs -r docker stop | xargs -r docker rm &&  docker volume prune -af && docker system prune -af"
alias ga='git add'
alias gbc='git checkout -b'
alias gbd='git branch -d'
alias gbl='git branch --list'
alias gc='git commit -m'
alias gca='git commit -am'
alias gco='git checkout'
alias gd='git diff'
alias gl="git log --all --graph --pretty=format:'%C(auto)%h%d %s %C(bold blue)[%aN]%Creset %Cgreen%ad%Creset' --date=relative"
alias gpl='git pull'
alias gps='git push'
alias gr='git rebase -i'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gre='git restore *'
alias gs='git status'
alias gsi='git submodule update --init --recursive'
alias gsu='git submodule update'
alias gsw='git switch'
alias ta='tmux attach'
alias tn='tmux new -s'
alias cd='z'

# ZSH OPTIONS
export HISTFILE="$XDG_CACHE_HOME/.zsh_history"
export HISTSIZE=10000
export SAVEHIST=10000
setopt APPEND_HISTORY
setopt AUTO_CD
setopt AUTO_LIST
setopt AUTO_PUSHD
setopt COMPLETE_IN_WORD
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt INC_APPEND_HISTORY
setopt MENU_COMPLETE
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt SHARE_HISTORY

# KEYBINDS
set KEYTIMEOUT=1
bindkey -s "^k" "kill **\t" # fzf: kill process
bindkey -s "^f" "^t"        # fzf: find file
bindkey -s "^d" "^[c"       # fzf: cd to dir
bindkey ";5C" forward-word
bindkey "5C" forward-word
bindkey ";5D" backward-word
bindkey "5D" backward-word

# TMUX
tmux new -d -s scratch 2> /dev/null

# PLUGINS
source $DOTFILES/dotfiles/antigen.zsh
antigen bundle fzf
antigen bundle ssh-agent
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen apply

# COMPLETIONS
autoload compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' complete true
zstyle ':completion:*' complete-options true
zstyle ':completion:*' use-cache on
zmodload zsh/complist

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# INITIALIZATIONS
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
