[icons]
icons = "material-nf"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = ""

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
disconnected_format = ""
format = " $icon "

[[block]]
block = "sound"
format = " $icon "
[icons.overrides]
volume = [
    "\U000f075f",
    "\U000f057f",
    "\U000f0580",
    "\U000f0580",
    "\U000f057e",
]
volume_muted = "MUTED"

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m  %R') "

